management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    instances:
      save-or-update-event-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      fetch-future-events-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      save-teams-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      fetch-pending teams-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      update-team-status-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      participant-past-events-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      participant-future-events-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      save-or-update-audience-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      audience-past-events-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      audience-future-events-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      audience-live-events-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      audience-unregistered-events-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      admin-inactive-events-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      update-event-status-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      fetch-event-details-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      fetch-team-details-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      unsent-email-count-for-audience-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      unsent-emails-for-audience-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      fetch-live-events-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      save-sub-user-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      update-sub-user-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      update-sub-user-active-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      verify-sub-user-credentials-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      verify-audience-ticket-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException