management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    instances:
      save-or-update-event-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      fetch-future-events-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      save-teams-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      fetch-pending teams-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      update-team-status-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      participant-past-events-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      participant-future-events-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException
      save-or-update-audience-retry:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - com.esportslan.microservices.esportslanapi.exceptions.BadRequestErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.InternalErrorException
          - com.esportslan.microservices.esportslanapi.exceptions.ValidationException